name: Build Cleanerr
on: [push]
jobs:
  Build-Cleanerr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          ./update.sh
        shell: bash
      - name: Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: cleanerr@github.actions
          build_dir: ./
          jekyll: no
